### ISSUE TITLE
Hard to understand

### ISSUE THREAD

**Issue by rigel-star** [sijanstu/Text-To-Voice-converter-in-java#1]
**

> Everything is in same class. Please partition in different classes so it will be easier to understand and also to contribute. Anyway it is great.

**

**Comment by sijanstu** [comment]
Thanks for valuable suggestions, I will make some changes to this code, try checking again after next commit. 🥇 
todo list:
-- developer friendly
-- copy-paste-run code

**Comment by sijanstu** [comment]
You can try understanding again. 💯
